// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// IMPORTANT: This file contains placeholder values that are NOT functional.
/// These placeholder values are safe to commit as they contain no real credentials.
///
/// To configure Firebase properly:
/// 1. Run `flutterfire configure` in your project root
/// 2. Select your Firebase project
/// 3. This file will be regenerated with real values
///
/// Alternatively, manually replace the values below with your Firebase Console config:
/// - Android: Add google-services.json to android/app/ and copy apiKey, appId, etc.
/// - iOS: Add GoogleService-Info.plist to ios/Runner/ and copy the relevant values
///
/// For development/demo mode, the app will run without Firebase
/// using mock data and local storage when initialization fails.
class DefaultFirebaseOptions {
  /// Returns the appropriate Firebase options for the current platform.
  ///
  /// Throws [UnsupportedError] if the platform is not supported.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Firebase options for Web platform.
  ///
  /// PLACEHOLDER: Replace with your actual Firebase Web configuration.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'autocheck-placeholder',
    authDomain: 'autocheck-placeholder.firebaseapp.com',
    storageBucket: 'autocheck-placeholder.appspot.com',
  );

  /// Firebase options for Android platform.
  ///
  /// PLACEHOLDER: Replace with your actual Firebase Android configuration.
  /// You also need to add google-services.json to android/app/
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'autocheck-placeholder',
    storageBucket: 'autocheck-placeholder.appspot.com',
  );

  /// Firebase options for iOS platform.
  ///
  /// PLACEHOLDER: Replace with your actual Firebase iOS configuration.
  /// You also need to add GoogleService-Info.plist to ios/Runner/
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'autocheck-placeholder',
    storageBucket: 'autocheck-placeholder.appspot.com',
    iosBundleId: 'com.autocheck.app',
  );

  /// Firebase options for macOS platform.
  ///
  /// PLACEHOLDER: Replace with your actual Firebase macOS configuration.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: '1:000000000000:macos:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'autocheck-placeholder',
    storageBucket: 'autocheck-placeholder.appspot.com',
    iosBundleId: 'com.autocheck.app',
  );

  /// Firebase options for Windows platform.
  ///
  /// PLACEHOLDER: Replace with your actual Firebase Windows configuration.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: '1:000000000000:windows:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'autocheck-placeholder',
    storageBucket: 'autocheck-placeholder.appspot.com',
  );
}
